# Generated by Django 4.2.7 on 2023-11-29 09:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bedaia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('firstdiscription', models.TextField()),
                ('seconddiscription', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('firstpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('secondpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('thirdpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('forthpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nukhba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('firstdiscription', models.TextField()),
                ('seconddiscription', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('firstpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('secondpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('thirdpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('forthpic', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
