# Generated by Django 4.2.7 on 2023-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedaia',
            name='firstpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='forthpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='secondpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='thirdpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='firstpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='forthpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='secondpic',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='thirdpic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
