# Generated by Django 4.2.7 on 2023-12-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_alter_bedaia_firstpic_alter_bedaia_forthpic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedaia',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nukhba',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
