# Generated by Django 4.2.7 on 2024-02-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_bedaia_video_file_nukhba_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedaia',
            name='upload_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nukhba',
            name='upload_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='firstpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='forthpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='secondpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='thirdpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='firstpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='forthpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='secondpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='thirdpic',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
