# Generated by Django 4.2.7 on 2024-02-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_bedaia_upload_file_nukhba_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedaia',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='upload_folder/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='video_file',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='upload_folder/'),
        ),
    ]
