# Generated by Django 4.2.7 on 2024-02-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_alter_bedaia_upload_file_alter_bedaia_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedaia',
            name='firstpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='forthpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='secondpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='bedaia',
            name='thirdpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='firstpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='forthpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='secondpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='nukhba',
            name='thirdpic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
